spring:
  application:
    name: chat-app
  datasource:
    url:  ${DATABASE_URL:jdbc:postgresql://localhost:5432/chat-app}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    redis:
      host: ${REDIS_URL:localhost}
      port: ${REDIS_PORT:6379}
application:
  session:
    token-ttl: ${SESSION_TOKEN_TTL:PT3H}
    refresh-token-ttl: ${SESSION_REFRESH_TOKEN_TTL:PT24H}
